//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirstApiApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attendence
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Attendence()
        {
            this.AttendenceupdateHistories = new HashSet<AttendenceupdateHistory>();
        }
    
        public int AttendenceId { get; set; }
        public int EmployeeId { get; set; }
        public System.DateTime TodayDate { get; set; }
        public Nullable<System.DateTime> AttendenceTime1 { get; set; }
        public Nullable<System.DateTime> LeavingTime1 { get; set; }
        public Nullable<System.DateTime> AttendenceTime2 { get; set; }
        public Nullable<System.DateTime> LeavingTime2 { get; set; }
    
        public virtual Employee Employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AttendenceupdateHistory> AttendenceupdateHistories { get; set; }
    }
}
