//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirstApiApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class BalanceDayOff
    {
        public int BalanceDayOffId { get; set; }
        public int EmployeeId { get; set; }
        public int DayNumDayOffRemain { get; set; }
        public int DayNumDayOffTaken { get; set; }
        public bool IsApproved { get; set; }
        public string Type { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
