//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirstApiApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class Disability
    {
        public int DisabilitiesId { get; set; }
        public long CertificateNumber { get; set; }
        public System.DateTime CertificateStartDate { get; set; }
        public string CertificatePlace { get; set; }
        public long RecordNumber { get; set; }
        public string Description { get; set; }
        public Nullable<int> EmployeeId { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
