//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirstApiApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class DisciplinaryAction
    {
        public int DisciplinaryId { get; set; }
        public System.DateTime Date { get; set; }
        public string Description { get; set; }
        public int value { get; set; }
        public string InvestigationSource { get; set; }
        public int EmpId { get; set; }
        public int ApprovedByEmployeeId { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Employee Employee1 { get; set; }
    }
}
