//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirstApiApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class DownLoadTransaction
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DownLoadTransaction()
        {
            this.DownLoadLogs = new HashSet<DownLoadLog>();
        }
    
        public int DownLoadTransactionId { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public int DeviceId { get; set; }
        public System.DateTime DateTime { get; set; }
    
        public virtual Device Device { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DownLoadLog> DownLoadLogs { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
