//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirstApiApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class Driver
    {
        public int DriversId { get; set; }
        public long LicenceNumber { get; set; }
        public short Degree { get; set; }
        public System.DateTime ExpirationDate { get; set; }
        public string PlaceOfLicence { get; set; }
        public Nullable<int> EmployeeId { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
