//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirstApiApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeVacationRequest
    {
        public int VacationRequestId { get; set; }
        public int EmployeeId { get; set; }
        public int VacationId { get; set; }
        public System.DateTime RequestDate { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public bool IsApproved { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Vacation Vacation { get; set; }
    }
}
