//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirstApiApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeDayOff
    {
        public int DayOffId { get; set; }
        public int EmployeeId { get; set; }
        public int DayOff { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
