//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirstApiApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeMilitaryStatu
    {
        public int EmployeeMilitaryStatusId { get; set; }
        public long ThirdNumber { get; set; }
        public System.DateTime CommittDate { get; set; }
        public long CertificateNumber { get; set; }
        public System.DateTime CertificateDate { get; set; }
        public System.DateTime FatherBirthDate { get; set; }
        public System.DateTime BrotherBirthDate { get; set; }
        public System.DateTime RequiredDate { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public Nullable<int> statusId { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual MililatryStatu MililatryStatu { get; set; }
    }
}
