//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirstApiApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class GeneralSetting
    {
        public int GeneralSettingId { get; set; }
        public System.DateTime MonthStartDate { get; set; }
        public string Language { get; set; }
        public string Theme { get; set; }
    }
}
