//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirstApiApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupingSetting
    {
        public int GroupingSettingId { get; set; }
        public int GroupId { get; set; }
        public System.DateTime StartDayTime { get; set; }
        public int Day { get; set; }
        public System.DateTime AttendenceTime { get; set; }
        public System.DateTime LeavingTime { get; set; }
        public bool IsWeekEnd { get; set; }
        public System.TimeSpan OverTimeBegin { get; set; }
        public System.TimeSpan FingerPrintConfirm { get; set; }
        public System.TimeSpan AllowedTime { get; set; }
    
        public virtual Grouping Grouping { get; set; }
    }
}
