//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirstApiApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class LateEarly
    {
        public int LateEarlyId { get; set; }
        public System.DateTime EarlyLateDate { get; set; }
        public System.TimeSpan OriginalPeriod { get; set; }
        public int LateEarlyType { get; set; }
        public bool IsApproved { get; set; }
        public int EmployeeId { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
