//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirstApiApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log
    {
        public int LogId { get; set; }
        public int EmployeeId { get; set; }
        public string Text { get; set; }
        public int ControllerId { get; set; }
        public int ActionId { get; set; }
        public System.DateTime Time { get; set; }
    
        public virtual Action Action { get; set; }
        public virtual Controller Controller { get; set; }
        public virtual User User { get; set; }
    }
}
