//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirstApiApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotificationTypeUser
    {
        public int NotificationTypeId { get; set; }
        public int EmployeeId { get; set; }
        public bool VisiblitySataus { get; set; }
    
        public virtual NotificationType NotificationType { get; set; }
        public virtual User User { get; set; }
    }
}
