//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirstApiApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class OverTime
    {
        public int OvertimeId { get; set; }
        public System.DateTime OvertimeDate { get; set; }
        public System.TimeSpan OverTimePeriod { get; set; }
        public Nullable<bool> Isapproved { get; set; }
        public int Type { get; set; }
        public int EmployeeId { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
