//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirstApiApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class PermissionRequestTo
    {
        public int PermissionRequestToId { get; set; }
        public int EmployeeId { get; set; }
        public int PermissionId { get; set; }
        public System.DateTime PermissionRequestDate { get; set; }
        public bool IsApproved { get; set; }
        public string Reason { get; set; }
        public System.TimeSpan TimeFrom { get; set; }
        public System.TimeSpan TimeTo { get; set; }
        public int PermissionNumber { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual PermissionType PermissionType { get; set; }
    }
}
