//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirstApiApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class TempDayOff
    {
        public int TempDayOffId { get; set; }
        public int EmployeeId { get; set; }
        public System.DateTime OriginalDate { get; set; }
        public System.DateTime InsteadDate { get; set; }
        public string Reason { get; set; }
        public int Type { get; set; }
        public bool IsApproved { get; set; }
        public System.DateTime RequestDate { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
