//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirstApiApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class VacationBalance
    {
        public int VacationBalanceId { get; set; }
        public int EmployeeId { get; set; }
        public int VacationId { get; set; }
        public int Balance { get; set; }
        public int Remain { get; set; }
        public int Year { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Vacation Vacation { get; set; }
    }
}
